language: php

notifications:
    on_success: change
    on_failure: change

php:
    - 7.0
    - 5.6
    - 5.3
    - 5.2
    - hhvm

env:
    # latest stable:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    # previous stable:
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=1
    # earliest supported:
    - WP_VERSION=3.1 WP_MULTISITE=0
    - WP_VERSION=3.1 WP_MULTISITE=1

matrix:
    exclude:
        # don't test 3.1 on hiphop:
        - php: hhvm
          env: WP_VERSION=3.1 WP_MULTISITE=0
        - php: hhvm
          env: WP_VERSION=3.1 WP_MULTISITE=1
        # don't test 3.1 on PHP 7:
        - php: 7.0
          env: WP_VERSION=3.1 WP_MULTISITE=0
        - php: 7.0
          env: WP_VERSION=3.1 WP_MULTISITE=1
    allow_failures:
        # allow failures on PHP 7 for now:
        - php: 7.0

install:
	# Install Composer
    - bash bin/install.sh

before_script:
	# Install WP test environment
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    # Check for PHP syntax errors
    - if [[ "$WP_VERSION" == "latest" ]]; then find . -path ./vendor -prune -o -name "*.php" -exec php -lf {} \;; fi;
    # Run phpunit
    - phpunit
    # Run Behat
    - bash bin/script.sh
