# run on container environment
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

language: php

notifications:
    email:
        on_success: change
        on_failure: always

php:
    - 7.1
    - 5.6
    - 5.3

env:
    # nightly:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1
    # latest stable:
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.7 WP_MULTISITE=1
    # earliest supported version with a non-buggy unit test suite:
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1

matrix:
    exclude:
        # don't test 4.0 on PHP 7+:
        - php: 7.1
          env: WP_VERSION=4.0 WP_MULTISITE=0
        - php: 7.1
          env: WP_VERSION=4.0 WP_MULTISITE=1
    allow_failures:
        # allow failures on nightlies:
        - env: WP_VERSION=nightly WP_MULTISITE=0
        - env: WP_VERSION=nightly WP_MULTISITE=1

before_install:
    - phpenv config-rm xdebug.ini

install:
    - composer install

before_script:
    - php --version
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - bash bin/script.sh
